[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno --open-console --baudrate 57600 -P COM5" # what the fuck?

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mangled-names"]
